#!/usr/bin/env python3
# encoding=utf-8
"""
gen_personas.py - regenerate default/data/soar_apps/medadvice_idp/
medadvice_idp_consts.py from the TA's ES identity lookup
(lookups/medadvice_identities.csv).

The SOAR stub app embeds the MedAdvice workshop personas so that `get user`
returns something recognisable for t.nguyen, x.collins, j.lee and friends
without contacting any directory. Keeping the table generated from the same CSV
that ES uses for entity attribution means the two never drift.

Usage:
    python3 tools/soar/gen_personas.py          # rewrite the consts module
    python3 tools/soar/gen_personas.py --check  # exit 1 if the module is stale

Dev-only: tools/ never ships in the TA tarball.

Copyright 2026 Splunk Inc.
Licensed under Apache License 2.0
"""

import csv
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
APP_ROOT = os.path.dirname(os.path.dirname(HERE))
CSV_PATH = os.path.join(APP_ROOT, 'lookups', 'medadvice_identities.csv')
OUT_PATH = os.path.join(APP_ROOT, 'default', 'data', 'soar_apps', 'medadvice_idp',
                        'medadvice_idp_consts.py')

HEADER = '''# encoding=utf-8
# medadvice_idp_consts.py - GENERATED by tools/soar/gen_personas.py from
# lookups/medadvice_identities.csv. Do not edit by hand; rerun the generator.
#
# Every persona here is a workshop fixture. The connector never contacts a
# directory and every result it returns carries "simulated": true.
#
# Copyright 2026 Splunk Inc.
# Licensed under Apache License 2.0

DIRECTORY_DEFAULT = "medadvice.example.com"
MODE_DEFAULT = "simulate"

MSG_TEST_OK = "MedAdvice IdP simulator ready (mode={mode}, directory={directory})"
MSG_MODE_UNSUPPORTED = "Unsupported mode '{mode}': only 'simulate' is implemented"
MSG_TOKEN_UNRESOLVED = ("username '{value}' looks like an unresolved token - "
                        "supply the actual username (e.g. t.nguyen)")
MSG_USERNAME_MISSING = "username is required"
MSG_DISABLED = "Account {username} disabled (simulated)"
MSG_ENABLED = "Account {username} enabled (simulated)"
MSG_SESSIONS_CLEARED = "{count} session(s) for {username} revoked (simulated)"
MSG_GET_USER = "User {username} retrieved (simulated, {known})"
MSG_LIST_SESSIONS = "{count} active session(s) for {username} (simulated)"

# Synthetic org attributes. Assigned deterministically from the username so the
# same persona always looks the same across attendees and reruns.
DEPARTMENTS = [
    "Clinical Operations", "Patient Services", "Pharmacy", "Nursing",
    "Care Coordination", "Billing", "IT - Clinical Systems", "Research",
]
CLIENT_ADDRESSES = ["76.87.129.168", "198.51.100.77", "203.0.113.42"]
SESSION_APP = "MedAdvice DemoBot"

# username -> persona. `known` distinguishes CSV personas from synthesised ones.
PERSONAS = {
'''

FOOTER = '''}

EMAIL_INDEX = dict((p["email"].lower(), u) for u, p in PERSONAS.items())
'''


def render():
    rows = []
    with io.open(CSV_PATH, encoding='utf-8', newline='') as handle:
        for row in csv.DictReader(handle):
            rows.append(row)
    rows.sort(key=lambda r: r['identity'])
    out = [HEADER]
    for row in rows:
        username = row['identity'].strip().lower()
        first = row['first'].strip()
        last = row['last'].strip()
        display = '{} {}'.format(first if len(first) > 1 else first + '.', last)
        out.append(
            '    "{u}": {{"username": "{u}", "email": "{e}", "display_name": "{d}",\n'
            '        "first_name": "{f}", "last_name": "{l}", "business_unit": "{b}",\n'
            '        "category": "{c}", "watchlist": {w}, "priority": "{p}", "known": True}},\n'
            .format(u=username, e=row['email'].strip().lower(), d=display, f=first,
                    l=last, b=row['bunit'].strip(), c=row['category'].strip(),
                    w='True' if row['watchlist'].strip().lower() == 'true' else 'False',
                    p=row['priority'].strip()))
    out.append(FOOTER)
    return ''.join(out)


def main(argv):
    text = render()
    if '--check' in argv:
        current = ''
        if os.path.exists(OUT_PATH):
            with io.open(OUT_PATH, encoding='utf-8') as handle:
                current = handle.read()
        if current != text:
            print('STALE: {} does not match {}; rerun gen_personas.py'.format(
                OUT_PATH, CSV_PATH), file=sys.stderr)
            return 1
        print('OK: {} is in sync with {}'.format(OUT_PATH, CSV_PATH))
        return 0
    with io.open(OUT_PATH, 'w', encoding='utf-8') as handle:
        handle.write(text)
    print('Wrote {} ({} personas)'.format(OUT_PATH, text.count('"known": True')))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
